---
output: 
  html_document:
    theme: yeti
    toc: false
    toc_float: false
    collapsed: false
    smooth_scroll: false
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>

## *Stochastic Actor-Based Models (SABMs)*

----

<br>

These lectures examine the logic of simulation based models for network dynamics. Specifically, the stochastic actor-based model (SABM) is an approach to modeling change in network panel data. The first lecture discusses the basic logic of the model. The first lab (Introduction to SABMs) provides an overview the RSiena package by examining the evolution of an advice network among 75 MBA students (see http://www.stats.ox.ac.uk/~snijders/siena/ for details). The second lecture discusses co-evolution of networks and behavior. The second lab (Co-Evolution of Networks and Behavior) examines co-evolution using the RSiena package. A comprehensive archive of materials, discussion, syntax, papers, etc. for the RSiena package is available at the Siena website.

<br>

#### Lecture Materials  

  + [Introduction to SABMs lecture](_lectures/lecture-10-sabm-intro.pdf)
  
  + Introduction to SABMs lab ([html](_labs\lab-11-sabm-intro.html)) ([Rmd](_labs\lab-11-sabm-intro.Rmd))
    
    + Advice networks (W1 .csv) (W2 .csv) (W3 .csv) for lab
    
    + Attribute data (rating .csv) for lab
    
  + [Co-Evolution of Networks and Behavior lecture](_lectures\lecture-11-sabm-coevolution.pdf)
  
  + Co-Evolution of Networks and Behavior lab ([html](_labs\lab-12-sabm-coevolution.html)) ([Rmd](_labs\lab-12-sabm-coevolution.Rmd))

<br>

____

<br>

#### ***Please*** report any needed corrections to the [Issues](https://github.com/jacobtnyoung/SAND/issues) page. Thanks!

<br>
<br>


###### ***Last updated `r format(Sys.time(), '%d %B, %Y')`***