---
output: 
  html_document:
    theme: yeti
    toc: false
    toc_float: false
    collapsed: false
    smooth_scroll: false
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set( echo = TRUE )
```

<br>

## Statistical Analysis of Network Data

This course provides a survey of the various tools used when analyzing networks. The overarching goal of the course is that, upon completion, students will be capable of developing research questions from a network perspective and incorporating network-based tools in their own research. The course is designed to be primarily methodological, dedicating the majority of the time to working through the mechanics of network-based tools. Students will also gain experience with [R](https://cran.r-project.org/), a commonly used software program for network data management, analysis, and visualization.  


Even if you are not taking the course, feel free to browse the lecture notes and labs. As always, I welcome any [feedback](https://github.com/jacobtnyoung/SAND/issues)!

<br>

*File Formats*  

Lectures are provided in .pdf format. Labs are provided in .html format and RMarkdown (.Rmd) format. The .html files can be opened by first downloading the file and then opening it using any web browser. The .Rmd files can be opened in any web browser, but require [RStudio](https://www.rstudio.com/) to [knit](https://cran.r-project.org/web/packages/knitr/index.html).  

<br>


## *Lecture Notes and Labs*  
____


[Introduction to Network Analysis](topics/page-01-intro.html)

[Introduction to R, R Studio, and Data-Driven Documents](topics/page-02-r-markdown.html)

[Network Data Structures and Network Data in R](topics/page-02-network-data.html)

[Network Description & Visualization](topics/page-04-description-visualization.html)

[Centrality](topics/page-05-centrality.html)

[Cohesive Subgroups](topics/page-06-subgroups.html)

[Bipartite Graphs/Two-Mode Networks, Projection, and Weighted Graphs](topics/page-07-bipartite.html)

[Exponential Random Graph Models (ERGMs)](topics/page-08-ergm.html)

[Stochastic Actor-Based Models (SABMs)](topics/page-09-sabm.html)

[Dynamic Network Visualization](topics/page-10-dynamic-visualization.html)

[Dynamic Network Visualization](topics/page-11-stergms.html)

[Sequential Temporal Exponential Random Graph Models (STERGMs)](topics/page-11-stergms.html)

[Epidemic Modeling](topics/page-12-epidemics.html)


<br>

____

<br>

#### ***Please*** report any needed corrections to the [Issues](https://github.com/jacobtnyoung/SAND/issues) page. Thanks!

<br>
<br>


###### ***Last updated `r format(Sys.time(), '%d %B, %Y')`***