---
output: 
  html_document:
    theme: yeti
    toc: false
    toc_float: false
    collapsed: false
    smooth_scroll: false
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<br>

## Network Data Structures and Sources of Network Data

These lectures cover the basics of using matrices to represent networks. Fundamental concepts of graph theory are also introduced. Also, various sources of network data are discussed. Special attention is given to the [Prison Inmate Network Study (PINS)](http://justicecenter.psu.edu/research/projects/%20prison-inmate-networks-study-pins) and the [Boston Special Youth Project](https://jacobtnyoung.github.io/SYP-Networks/) (SYP) Affiliation data.

*Files*:
* Data structures lecture ([pdf](lectures/crj_605_networks_2_data_structures_slides.pdf))
* Sources of data lecture ([pdf](lectures/crj_605_networks_3_sources_of_data_slides.pdf))
* R script for Data structures lecture ([.R](lecture_syntax/crj_605_networks_2_data_structures_syntax.R))

<br>

____

<br>

#### ***Please*** report any needed corrections to the [Issues](https://github.com/jacobtnyoung/SAND/issues) page. Thanks!

<br>
<br>


###### ***Last updated `r format(Sys.time(), '%d %B, %Y')`***