---
output: 
  html_document:
    theme: yeti
    toc: false
    toc_float: false
    collapsed: false
    smooth_scroll: false
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<br>

## Getting Started with R and Network Visualization

This section starts working in [R](http://cran.r-project.org/) and focuses on three goals: First, an introduction to [R](http://cran.r-project.org/) (Intro to R lab) to familiarize users with [R](http://cran.r-project.org/). Second, an introduction to network analysis in [R](http://cran.r-project.org/) (Intro to Networks lab) covers how network objects are created and manipulated using the [sna](https://cran.r-project.org/web/packages/sna/index.html) package. Third, basic network visualization is reviewed (Visualization lab) using the [sna](https://cran.r-project.org/web/packages/sna/index.html) package.

*Files*:
* Intro to R lab ([html](labs/CRJ_605_Networks_1_INTRO_R_lab.html)) ([Rmd](labs/CRJ_605_Networks_1_INTRO_R_lab.Rmd))
* Intro to Networks lab (html) (Rmd)
* Visualization lab (html) (Rmd)
* Example networks used in labs (undirected network) (directed network)

<br>

____

<br>

#### ***Please*** report any needed corrections to the [Issues](https://github.com/jacobtnyoung/SAND/issues) page. Thanks!

<br>
<br>


###### ***Last updated `r format(Sys.time(), '%d %B, %Y')`***