---
title: Statistical Analysis of Network Data
output: 
  html_document:
    theme: yeti
    toc: false
    toc_float: false
    collapsed: false
    smooth_scroll: false
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set( echo = TRUE )
```

<br>

## *Introduction to Network Analysis*  
____

The introductory lecture covers the basics of network analysis: what it is, why we do it, etc. 

The learning goals of this lecture are to:   

  1) understand the difference between individual vs. network approaches to research   
  2) introduce basic data elements in network analysis

<br>


#### Lecture Materials

 + [Introduction lecture](../lectures/lecture-01-introduction.pdf) 
 
 + [R script for Introduction lecture](../lecture_syntax/lecture-syntax-01-introduction.R)

<br>

#### Course Survey Materials

 + Raw course survey data
   + [Wave 1]()
   
   + [Wave 2]()
   
   + [Wave 1 & Wave 2]()
 
 
  + Course survey data instruments
    + [Wave 1 instrument]() 
    
    + [Wave 2 instrument]()
    
    + [R script to clean raw course survey data from Wave 1]()
    
    + [R script to clean raw course survey data from Wave 1 & Wave 2]()
 
<br>
 
#### Adjacency matrices for course survey data:

##### Wave 1

  + [Spend time net]()
  
  + [Talk about course net]()
  
  + [Trust net]()
  
  + [TV net]()

<br>

##### Wave 2

  + [Spend time net]()
  
  + [Talk about course net]()
  
  + [Trust net]()

<br>  

##### R data file with cleaned course survey data and network objects
  
  + [Wave 1]()
  
  + [Wave 1 & 2]()

<br>

____

<br>

#### ***Please*** report any needed corrections to the [Issues](https://github.com/jacobtnyoung/SAND/issues/new) page. Thanks!

<br>
<br>


###### ***Last updated `r format(Sys.time(), '%d %B, %Y')`***