---
title: Statistical Analysis of Network Data
author: Jacob T.N. Young
output: 
  html_document:
    theme: yeti
    toc: false
    toc_float: false
    collapsed: false
    smooth_scroll: false
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set( echo = TRUE )
```


<br>

## *Bipartite Graphs/Two-Mode Networks*

----

<br>


These lectures examine data that are two-mode. That is, data in which objects in one modality (e.g. people) are connected through a second modality (e.g. clubs). 

The first lecture and the accompanying lab provides an overview of how to create adjacency matrices from two-mode networks and how to analyze bipartite graphs. 

The second lecture and lab focus on projecting two-mode networks to one-mode (i.e. unipartite graphs) and the consequent weighting of edges that occurs. 

A problem set (with solutions) is provided to work through the material covered.

<br>

#### Lecture Materials  

  + [Bipartite Graphs lecture](_lectures\lecture-07-bipartite.pdf)
  
  + Lab 07-Bipartite Graphs/Two-Mode Networks ([html](_labs\lab-07-bipartite.html)) ([Rmd](_labs\lab-07-bipartite.Rmd))
  
    + Two-mode edgelist (.csv) from Young & Ready (2015) used in Bipartite Graphs lecture & Bipartite Graphs lab  
  <br>
  
  + Bipartite Graphs problem set (pdf, see Part B) and solutions (html) (Rmd)
  
  + [Projection & Weighted Graphs lecture](_lectures\lecture-08-projection-weighted.pdf)
  
  + Lab 08-Projection & Weighted Graphs ([html](_labs\lab-08-projection-weighted.html)) ([Rmd](_labs\lab-08-projection-weighted.Rmd))

<br>

____

<br>

#### ***Please*** report any needed corrections to the [Issues](https://github.com/jacobtnyoung/SAND/issues) page. Thanks!

<br>
<br>


###### ***Last updated `r format(Sys.time(), '%d %B, %Y')`***