---
title: Statistical Analysis of Network Data
author: Jacob T.N. Young
output: 
  html_document:
    theme: yeti
    toc: false
    toc_float: false
    collapsed: false
    smooth_scroll: false
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set( echo = TRUE )
```


<br>

## *Stochastic Actor-Based Models (SABMs)*

----

<br>

These lectures examine the logic of simulation based models for network dynamics. Specifically, the stochastic actor-based model (SABM) is an approach to modeling change in network panel data. The first lecture introduces the basic logic of the model and the first lab (Introduction to SABMs) provides an overview of this content in R using the `RSiena`. The second lecture discusses co-evolution of networks and behavior and the second lab (Co-Evolution of Networks and Behavior) examines co-evolution using the `RSiena` package.

<br>

#### Lecture & Lab Materials  

  + [Introduction to Stochastic Actor-Based Models (SABMs) lecture](../lectures/lecture-09-sabm-intro.pdf)  
  + [Coevolution of Networks and Behavior using Stochastic Actor-Based Models (SABMs) lecture](../lectures/lecture-10-sabm-coev.pdf)
  
  <br>

  + [Introduction to Stochastic Actor-Based Models (SABMs) in R lab](../labs/lab-12-sabm-intro.html)
  + [Coevolution of Networks and Behavior using Stochastic Actor-Based Models (SABMs) in R lab](../labs/lab-13-sabm-coev.html)

<br>

____

<br>

<p align="center">
[Back to SAND main page](https://jacobtnyoung.github.io/SAND/)
</p>

<br>

<br>

#### ***Please*** report any needed corrections to the [Issues](https://github.com/jacobtnyoung/SAND/issues/new) page. Thanks!

<br>
<br>