---
title: Statistical Analysis of Network Data
author: Jacob T.N. Young
output: 
  html_document:
    theme: yeti
    toc: false
    toc_float: false
    collapsed: false
    smooth_scroll: false
---

<style>
body {
text-align: left}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set( echo = TRUE )
```

<br>

## *Network Data Structures & Network Data in R*

____

This week, we will first cover the basics of using matrices to represent networks. You will be introduced to the fundamental concepts of graph theory. We will then work through how these data structures are created as objects in R. This week will also assign Homework 2 and provides a template to aid in completing the assignment.

<br>

#### Lecture & Lab Materials  

  + [Network Data Structures lecture](../lectures/lecture-02-data-structures.pdf)  
  
  + [Introduction to Networks in R lab](../labs/lab-03-network-data.html)  

<br>

#### Homework Materials  

  + [Homework 2 instructions](../hmwk/hmwk-02-instructions.html)  
  
  + [Homework 2 template](../labs/templates/hmwk-02-template.zip?raw=true)  
  
<br>

____

<br>

<p align="center">
[Back to SAND main page](https://jacobtnyoung.github.io/SAND/)
</p>

<br>

<br>

#### ***Please*** report any needed corrections to the [Issues](https://github.com/jacobtnyoung/SAND/issues/new) page. Thanks!

<br>
<br>