---
title: Statistical Analysis of Network Data
author: Jacob T.N. Young
output: 
  html_document:
    theme: yeti
    toc: false
    toc_float: false
    collapsed: false
    smooth_scroll: false
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set( echo = TRUE )
```


<br>

## *Exponential Random Graph Models (ERGMs)*

----

<br>

These lectures examine the logic of generative models for network data.   

The lecture introduces the exponential random graph model (ERGM) as a flexible tool for specifying network configurations that generate global network structures.  

The first lab provides an overview of different dependence specifications of the model (e.g. dyadic independence) and working with node level attributes using the ergm package.  

The second lab (Simulation and Goodness of Fit) examines functions for goodness of fit and simulation in the ergm package. A comprehensive archive of materials, discussion, syntax, papers, etc. for the ergm package is available at the statnet website.  

A problem set (with solutions) is provided to work through the material covered.

<br>

#### Lecture Materials  

  + [Introduction to ERGMs lecture](../lectures/lecture-09-ergm-intro.pdf)
  
  + [R script for Introduction to ERGMs lecture](../lecture_syntax/lecture-syntax-09-ergm-intro.R)
  
  + [Lab 09-Introduction to Exponential Random Graph Models (ERGMs)](../labs/lab-09-ergm-intro.html)
  
  + [Lab 10-Simulation and Goodness of Fit with Exponential Random Graph Models (ERGMs)](../labs/lab-10-ergm-gof.html)
  
  + ERGMs problem set (pdf) and solutions (html) (Rmd)

<br>

____

<br>

#### ***Please*** report any needed corrections to the [Issues](https://github.com/jacobtnyoung/SAND/issues) page. Thanks!

<br>
<br>


###### ***Last updated `r format(Sys.time(), '%d %B, %Y')`***