---
title: Statistical Analysis of Network Data
author: Jacob T.N. Young
output: 
  html_document:
    theme: yeti
    toc: false
    toc_float: false
    collapsed: false
    smooth_scroll: false
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set( echo = TRUE )
```


<br>

## *Cohesive Subgroups*

----

<br>

This lecture provides an introduction to the conceptualization of cohesion in networks. The lecture examines various operationalizations of cohesion by examining definitions of subgroups. Specifically, the lecture covers:  

  + cliques
  
  + *n*-cliques 
  
  + *k*-cores
  
  + community detection algorithms  
  
The accompanying lab provide an overview of these measures using the [igraph](https://igraph.org/redirect.html) and the [sna](https://cran.r-project.org/web/packages/sna/index.html) package in [R](http://cran.r-project.org/).

<br>

#### Lecture Materials  

  + [Identifying Subgroups lecture](../lectures/lecture-06-subgroups.pdf)
  
  + [R script for Identifying Subgroups lecture](../lecture_syntax/lecture-syntax-06-subgroups.R)
  
  + Lab 06-Identifying Cohesive Subgroups ([html](../labs/lab-06-subgroups.html)) ([Rmd](../labs/lab-06-subgroups.Rmd))

<br>

____

<br>

#### ***Please*** report any needed corrections to the [Issues](https://github.com/jacobtnyoung/SAND/issues) page. Thanks!

<br>
<br>


###### ***Last updated `r format(Sys.time(), '%d %B, %Y')`***