---
title: Statistical Analysis of Network Data
author: Jacob T.N. Young
output: 
  html_document:
    theme: yeti
    toc: false
    toc_float: false
    collapsed: false
    smooth_scroll: false
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set( echo = TRUE )
```


<br>

## *Centrality*

----

<br>

This lecture provides an introduction to centrality measures for individual nodes as well as centralization measures for graphs. In particular, the following centrality measures are described:  

  + Degree  
  
  + Closeness  
  
  + Betweenness
  
The accompanying labs provide an overview of these measures using the [sna](https://cran.r-project.org/web/packages/sna/index.html) package in [R](http://cran.r-project.org/). In addition, a problem set (with solutions) is provided to work through the material covered.

<br>

#### Lecture Materials  

<br>

  + **Degree Centrality**
  
    + [Degree Centrality lecture](../lectures/lecture-04-degree-centrality.pdf) 
  
    + [R script for Degree Centrality lecture](../lecture_syntax/lecture-syntax-04-degree-centrality.R)
  
    + Lab 04-Degree Centrality and Centralization ([html](../labs/lab-04-degree-centrality.html)) ([Rmd](../labs/lab-04-degree-centrality.Rmd))
  
    + Degree Centrality problem set (pdf) and solutions (html) (Rmd)
  
  <br>

  + **Closeness & Betweeness Centrality**
  
    + [Closeness & Betweenness Centrality lecture](../lectures/lecture-05-close-between-centrality.pdf)
    
    + [R script for Closeness & Betweenness Centrality lecture](../lecture_syntax/lecture-syntax-05-close-between-centrality.R)
  
    + Lab 05-Closeness & Betweenness Centrality/Centralization ([html](../labs/lab-05-close-between-centrality.html)) ([Rmd](../labs/lab-05-close-between-centrality.Rmd))
  
    + Betweenness Centrality problem set (pdf, see Part A) and solutions (html) (Rmd)

<br>

____

<br>

#### ***Please*** report any needed corrections to the [Issues](https://github.com/jacobtnyoung/SAND/issues) page. Thanks!

<br>
<br>


###### ***Last updated `r format(Sys.time(), '%d %B, %Y')`***