---
title: "Homework 1 - Introduction to Network Analysis - INSTRUCTIONS"
date: "CRJ 605 Statistical Analysis of Network Data"
output: 
  html_document:
    df_print: paged
    theme: cosmo
    highlight: haddock
    toc: yes
    toc_float: yes
    code_fold: show
    self_contained: true
---

<style>
body {
text-align: left}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

For the first homework, I would like you to construct a network. Think about a type of relationship that is interesting, important, etc. and what it connects. Whatever floats your boat. It can be a real example from your life, something fictitious, anything really. 

**IMPORTANT**: *read through the instructions completely before deciding what you will choose*.

## Part I

*After making your decision, do the following*:

### A. Describe the network 

  1. Is the network one mode or multi-mode?
  2. What do the points (i.e. nodes) represent? (note: if multiple modes, be sure to describe each mode)
  3. What do the ties (i.e. edges) represent?
  4. Are the ties simplex or multiplex? (note: if multiplex, be sure to describe each edge)
  5. Are the ties undirected or directed? Binary/Weighted/Signed?
  6. Why type of edge is it? (social relationship? Interactions? Flow?)
  7. Why did you pick this network?
    
### B. Draw a picture of the network (by hand is fine)
  
<br>

## Part II

*After completing Part I, do the following*:

### Choose a new network and repeat Part I

<br>

## Submission and Due Date

A physical copy of the assignment must be turned in during class on the corresponding due date. This assignment is *DUE* on **1/24**.

<br>

____

<br>

<p align="center"> [Back to SAND main page](https://jacobtnyoung.github.io/SAND/) </p>

<br>

##### ***Please*** report any needed corrections to the [Issues](https://github.com/jacobtnyoung/SAND/issues/new) page. Thanks!

<br>
<br>


###### ***Last updated `r format(Sys.time(), '%d %B, %Y')`***